In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\ssayc\HandsOnRec\data\projectinfo.csv')

In [3]:
df

,fullname,analyzed,cloneurl,commits_count,created_at,default_branch,description,errormsg,error_commits_count,filtered,...,owner,pushed_at,query,size,stargazers_count,status,updated_at,watchers_count,tf,firstcommit
0,Bearded-Hen/Android-Bootstrap,f,https://github.com/Bearded-Hen/Android-Bootstr...,326,2013-11-01 15:36:17,master,"Bootstrap style widgets for Android, with Glyp...",NaN,0,f,...,Bearded-Hen,2017-04-18 07:20:35,language:java,11401,5966,ANALYZED,2017-05-28 05:29:57,5966,1.0,2013-11-01 13:36:17
1,mediaelement/mediaelement,f,https://github.com/mediaelement/mediaelement.git,4315,2010-07-28 02:32:56,master,HTML5 <audio> or <video> player with support f...,NaN,0,f,...,mediaelement,2017-05-26 19:13:46,language:javascript,56956,4921,ANALYZED,2017-05-29 12:45:00,4921,1.0,2010-07-27 23:35:01
2,redis-store/redis-store,f,https://github.com/redis-store/redis-store.git,565,2009-04-11 14:15:41,master,"Namespaced Rack::Session, Rack::Cache, I18n an...",NaN,0,f,...,redis-store,2017-05-05 13:33:38,language:ruby,2931,1357,ANALYZED,2017-05-26 21:15:34,1357,1.0,2009-04-11 07:54:41
3,magento/magento2,f,https://github.com/magento/magento2.git,53219,2011-11-30 15:30:13,develop,All Submissions you make to Magento Inc. (“Mag...,NaN,0,f,...,magento,2017-05-29 21:10:22,language:php,367432,4424,ANALYZED,2017-05-29 22:07:11,4424,1.0,2011-11-30 13:29:43
4,spinnaker/spinnaker,f,https://github.com/spinnaker/spinnaker.git,1390,2014-07-02 19:02:36,master,"Spinnaker is an open source, multi-cloud conti...",NaN,0,f,...,spinnaker,2017-05-27 01:35:13,language:python,2441,3036,ANALYZED,2017-05-29 16:33:49,3036,2.0,2014-09-07 06:01:23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,mlpack/mlpack,f,https://github.com/mlpack/mlpack.git,16348,2014-12-17 18:16:59,master,mlpack: a scalable C++ machine learning librar...,NaN,0,f,...,mlpack,2017-05-30 09:36:19,language:c++ language:c,239521,1520,ANALYZED,2017-05-29 22:43:50,1520,2.0,1969-12-31 21:00:00
2996,cleanflight/cleanflight,f,https://github.com/cleanflight/cleanflight.git,8612,2013-03-27 23:49:19,master,Clean-code version of the baseflight flight co...,NaN,0,f,...,cleanflight,2017-05-30 01:00:48,language:c++ language:c,141266,1605,ANALYZED,2017-05-29 09:34:16,1605,3.0,2012-02-16 07:39:58
2997,awesome-print/awesome_print,f,https://github.com/awesome-print/awesome_print...,436,2010-04-03 04:45:43,master,Pretty print your Ruby objects with style -- i...,NaN,0,f,...,awesome-print,2017-04-18 00:41:31,language:ruby,713,3083,ANALYZED,2017-05-28 16:31:47,3083,3.0,NaN
2998,trogdoro/xiki,f,https://github.com/trogdoro/xiki.git,1085,2008-06-05 01:03:11,master,A shell console with GUI features,NaN,0,f,...,trogdoro,2016-11-16 23:59:59,language:ruby,6989,3433,ANALYZED,2017-05-25 11:52:04,3433,1.0,2008-06-04 21:57:33
2999,lynndylanhurley/devise_token_auth,f,https://github.com/lynndylanhurley/devise_toke...,762,2014-06-29 22:43:58,master,Token based authentication for Rails JSON APIs...,NaN,0,f,...,lynndylanhurley,2017-05-26 18:36:31,language:ruby,7932,1947,ANALYZED,2017-05-29 02:36:05,1947,1.0,2014-06-29 04:16:04

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fullname             3000 non-null   object
 1   analyzed             3000 non-null   object
 2   cloneurl             3000 non-null   object
 3   commits_count        3000 non-null   int64
 4   created_at           3000 non-null   object
 5   default_branch       3000 non-null   object
 6   description          2968 non-null   object
 7   errormsg             677 non-null    object
 8   error_commits_count  3000 non-null   int64
 9   filtered             3000 non-null   object
 10  filterinfo           677 non-null    object
 11  fork                 3000 non-null   object
 12  forks_count          3000 non-null   int64
 13  homepage             1778 non-null   object
 14  language             3000 non-null   object
 15  lastcommit           2987 non-null   object
 16  mainlanguage         2998 non-null   object
 17  name                 2999 non-null   object
 18  numauthors           3000 non-null   int64
 19  numfiles             3000 non-null   int64
 20  open_issues          3000 non-null   int64
 21  owner                3000 non-null   object
 22  pushed_at            3000 non-null   object
 23  query                3000 non-null   object
 24  size                 3000 non-null   int64
 25  stargazers_count     3000 non-null   int64
 26  status               3000 non-null   object
 27  updated_at           3000 non-null   object
 28  watchers_count       3000 non-null   int64
 29  tf                   2992 non-null   float64
 30  firstcommit          1978 non-null   object
dtypes: float64(1), int64(9), object(21)
memory usage: 480.5+ KB

In [8]:
df['size']

0        11401
1        56956
2         2931
3       367432
4         2441
         ...
2995    239521
2996    141266
2997       713
2998      6989
2999      7932
Name: size, Length: 3000, dtype: int64

In [7]:
df.describe()

,commits_count,error_commits_count,forks_count,numauthors,numfiles,open_issues,size,stargazers_count,watchers_count,tf
count,3000.000000,3000.0,3000.000000,3000.000000,3000.000000,3000.000000,3.000000e+03,3000.000000,3000.000000,2992.000000
mean,3754.766667,0.0,1012.986000,118.784000,1029.550333,136.533000,4.876320e+04,4830.793333,4830.793333,1.753676
std,20551.248239,0.0,1865.920092,474.262563,3901.469475,278.337317,2.959570e+05,7718.399912,7718.399912,1.801728
min,0.000000,0.0,27.000000,0.000000,1.000000,0.000000,0.000000e+00,796.000000,796.000000,0.000000
25%,241.000000,0.0,271.000000,17.000000,61.000000,18.000000,1.223000e+03,1886.250000,1886.250000,1.000000
50%,725.000000,0.0,532.500000,45.000000,162.000000,51.000000,4.862000e+03,2874.000000,2874.000000,1.000000
75%,2076.250000,0.0,1066.500000,105.000000,563.250000,142.000000,2.200175e+04,5475.000000,5475.000000,2.000000
max,678122.000000,0.0,51209.000000,14970.000000,67804.000000,4467.000000,1.147366e+07,277888.000000,277888.000000,26.000000

In [63]:
projects = df[['name', 'owner', 'description', 'status','numauthors', 'mainlanguage', 'open_issues', 'tf', 'forks_count', 'lastcommit']]

In [64]:
projects.head()

,name,owner,description,status,numauthors,mainlanguage,open_issues,tf,forks_count,lastcommit
0,Android-Bootstrap,Bearded-Hen,"Bootstrap style widgets for Android, with Glyp...",ANALYZED,25,Java,16,1.0,1337,2017-04-18 04:20:34
1,mediaelement,mediaelement,HTML5 <audio> or <video> player with support f...,ANALYZED,242,JavaScript,2,1.0,1137,2017-05-26 16:12:49
2,redis-store,redis-store,"Namespaced Rack::Session, Rack::Cache, I18n an...",ANALYZED,66,Ruby,5,1.0,303,2017-03-08 17:35:59
3,magento2,magento,All Submissions you make to Magento Inc. (“Mag...,ANALYZED,538,PHP,2491,1.0,3335,2017-05-29 07:14:45
4,spinnaker,spinnaker,"Spinnaker is an open source, multi-cloud conti...",ANALYZED,67,Python,174,2.0,460,2017-05-26 22:35:12

In [65]:
projects.tail()

,name,owner,description,status,numauthors,mainlanguage,open_issues,tf,forks_count,lastcommit
2995,mlpack,mlpack,mlpack: a scalable C++ machine learning librar...,ANALYZED,125,C++,84,2.0,572,2017-05-30 11:09:29
2996,cleanflight,cleanflight,Clean-code version of the baseflight flight co...,ANALYZED,245,C,14,3.0,1737,2017-06-01 04:07:53
2997,awesome_print,awesome-print,Pretty print your Ruby objects with style -- i...,ANALYZED,54,Ruby,73,3.0,233,2017-02-11 03:00:23
2998,xiki,trogdoro,A shell console with GUI features,ANALYZED,11,Ruby,112,1.0,205,2016-11-16 21:59:32
2999,devise_token_auth,lynndylanhurley,Token based authentication for Rails JSON APIs...,ANALYZED,110,Ruby,368,1.0,583,2017-05-26 15:36:30

In [66]:
projects.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          2999 non-null   object
 1   owner         3000 non-null   object
 2   description   2968 non-null   object
 3   status        3000 non-null   object
 4   numauthors    3000 non-null   int64
 5   mainlanguage  2998 non-null   object
 6   open_issues   3000 non-null   int64
 7   tf            2992 non-null   float64
 8   forks_count   3000 non-null   int64
 9   lastcommit    2987 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 164.1+ KB

In [ ]:
projects.shape()

In [67]:
projects.sort_values('tf', ascending=False)

,name,owner,description,status,numauthors,mainlanguage,open_issues,tf,forks_count,lastcommit
1056,edx-platform,edx,"The Open edX platform, the software that power...",ANALYZED,387,Python,190,26.0,1829,2017-05-28 01:59:22
1842,freebsd,freebsd,FreeBSD src tree (read-only mirror),ANALYZED,719,C,8,23.0,1156,2017-05-30 09:00:56
1484,FrameworkBenchmarks,TechEmpower,Source code for the framework benchmarking pro...,ANALYZED,381,PHP,41,22.0,904,2017-05-29 18:11:49
2663,odoo,odoo,Odoo. Open Source Apps To Grow Your Business.,ANALYZED,920,Python,3649,20.0,6207,2017-05-29 12:52:43
1740,php-src,php,The PHP Interpreter,ANALYZED,719,C,118,18.0,4048,2017-05-30 07:31:58
...,...,...,...,...,...,...,...,...,...,...
825,clearskies,jewel,Open source btsync clone,NOTCOMPUTED,12,NaN,5,NaN,50,2014-04-28 12:27:58
846,famous,Famous,This repo is being deprecated. Please check ou...,NOTCOMPUTED,79,JavaScript,4,NaN,797,2015-05-22 06:23:40
1500,awesome-awesomeness,bayandin,A curated list of awesome awesomeness,ANALYZED,160,Ruby,1,NaN,2417,2017-05-25 09:48:34
1800,libuv,joyent,Go to,NOTCOMPUTED,1,C,64,NaN,736,2014-11-26 18:53:02
2669,webkit.js,trevorlinton,Pure JavaScript Port of WebKit,NOTCOMPUTED,6,C++,21,NaN,80,2015-01-30 02:54:49

In [68]:
projects.sort_values('numauthors', ascending=False)

,name,owner,description,status,numauthors,mainlanguage,open_issues,tf,forks_count,lastcommit
1959,linux,torvalds,Linux kernel source tree,ANALYZED,14970,C,146,4.0,17213,2017-05-29 14:05:19
2786,linux,raspberrypi,Kernel source tree for Raspberry Pi Foundation...,ANALYZED,14300,C,98,3.0,2057,2017-05-26 11:00:18
1499,homebrew-core,Homebrew,🍻 Default formulae for the missing package man...,ANALYZED,7210,Ruby,67,3.0,2699,2017-05-29 15:22:58
1124,legacy-linuxbrew,Linuxbrew,":skull: This repository is defunct, because it...",ANALYZED,6407,Ruby,67,3.0,325,2016-04-27 03:41:45
2194,legacy-homebrew,Homebrew,:skull: The former home of Homebrew,ANALYZED,6362,Ruby,0,2.0,13548,2016-10-09 15:59:35
...,...,...,...,...,...,...,...,...,...,...
2774,flasky,miguelgrinberg,"Companion code to my O'Reilly book ""Flask Web ...",NOTCOMPUTED,1,Python,19,1.0,1829,2017-01-30 06:03:42
1611,grafika,google,Grafika test app,NOTCOMPUTED,1,Java,22,1.0,623,2014-05-22 15:30:51
2266,RecyclerViewSnap,rubensousa,RecyclerView snapping example with SnapHelper,NOTCOMPUTED,1,Java,2,1.0,271,2017-03-25 14:26:10
977,FlycoTabLayout,H07000223,An Android TabLayout Lib,NOTCOMPUTED,1,Java,52,1.0,1003,2017-04-27 05:50:12
168,miles-deep,ryanjay0,Deep Learning Porn Video Classifier/Editor wit...,NOTCOMPUTED,0,C++,4,NaN,187,NaN

In [75]:
projects[projects['numauthors'] <= 100].sort_values('numauthors', ascending=False)

,name,owner,description,status,numauthors,mainlanguage,open_issues,tf,forks_count,lastcommit
2872,ZendSkeletonApplication,zendframework,Skeleton application for zend-mvc projects,ANALYZED,100,PHP,10,2.0,1664,2017-03-11 03:17:47
2389,administrate,thoughtbot,A Rails engine that helps you put together a s...,ANALYZED,100,Ruby,139,1.0,489,2017-05-27 02:47:26
1254,n98-magerun,netz98,"The swiss army knife for Magento developers, s...",ANALYZED,100,PHP,107,2.0,365,2017-04-17 07:38:25
1382,vcap,cloudfoundry-attic,Cloud Foundry - the open platform as a service...,ANALYZED,100,Ruby,0,3.0,386,2013-08-27 21:38:34
102,packagist,composer,Package Repository Website - try https://packa...,ANALYZED,100,PHP,61,1.0,332,2017-05-23 12:20:00
...,...,...,...,...,...,...,...,...,...,...
977,FlycoTabLayout,H07000223,An Android TabLayout Lib,NOTCOMPUTED,1,Java,52,1.0,1003,2017-04-27 05:50:12
355,ZhihuDailyPurify,izzyleung,Purified version of Zhihu Daily - 更纯净的知乎日报,ANALYZED,1,Java,4,1.0,920,2016-08-25 23:06:28
449,keen,keendreams,Keen Dreams on Greenlight!,NOTCOMPUTED,1,C,2,1.0,149,2014-11-12 18:06:31
2777,SmartAppUpdates,cundong,Android应用增量更新,ANALYZED,1,C,13,1.0,741,2016-02-17 05:43:21
168,miles-deep,ryanjay0,Deep Learning Porn Video Classifier/Editor wit...,NOTCOMPUTED,0,C++,4,NaN,187,NaN

In [85]:
def first_take(df):
    #ask for language pref 
    print("Whats your favorite coding language:")
    lang = input()
    
    #ask what size project they want
    print("Do you want a large or small project?")
    size = input()
    #assign variables
    if size == 'small':
        min_issues = 0
        max_issues = 500
    else:
        min_issues = 500
        max_issues = 100000
    
    
    #ask responsibility load
    print("On a scale from 1-3 how much responsibility do you want?")
    resp = int(input())
    
    if resp == 1:
        min_authors = 2000
    elif resp == 2: 
        min_authors = 500
    elif resp == 3:
        min_authors = 2
        
    #create new variable to store preferred projects 
    proj = df.copy()
    
    #filter based on inputs 
    proj = proj[(proj['mainlanguage'] == lang) &
               (proj['open_issues'] >= min_issues) & 
               (proj['open_issues'] <= max_issues) & 
               (proj['numauthors'] >= min_authors)]

In [84]:
first_take(projects)

Whats your favorite coding language:
python
Do you want a large or small project?
small
On a scale from 1-3 how much responsibility do you want?
1